import {
  AppData,
  UserRole,
  ProcessingBatchStatus,
  CuppingSessionType,
  SCA_ATTRIBUTES,
  Farm,
  ActivityType,
  ProcessType,
  GreenBeanSourceType,
  RoastLevel,
} from "./types";

export const MOCK_DATA: AppData = {
  users: [
    {
      id: "user-headjudge",
      name: "Artanis",
      roles: [UserRole.HeadJudge],
      isActive: true,
    },
    {
      id: "user-cupper1",
      name: "Tassadar",
      roles: [UserRole.Cupper],
      isActive: true,
    },
    {
      id: "user-cupper2",
      name: "Zeratul",
      roles: [UserRole.Cupper],
      isActive: true,
    },
    {
      id: "user-cupper3",
      name: "Fenix",
      roles: [UserRole.Cupper],
      isActive: true,
    },
    {
      id: "user-roaster1",
      name: "Jim Raynor",
      roles: [UserRole.Roaster],
      isActive: true,
    },
    {
      id: "user-processor1",
      name: "Alarak",
      roles: [UserRole.Processor],
      isActive: true,
    },
  ],
  farms: [],
  harvestLots: [],
  processingBatches: [],
  parchmentLots: [],
  greenBeanLots: [
    // External purchases examples
    {
      id: "GBL003",
      sourceType: GreenBeanSourceType.External,
      grade: "Grade A",
      initialWeightKg: 60,
      currentWeightKg: 60,
      availabilityStatus: "Available",
      cuppingScores: [{ sessionId: "CS001", score: 86.5 }],
      externalSource: {
        originName: "Ethiopia Guji Cooperative",
        variety: "Heirloom",
        processType: "Natural",
        purchaseDate: "2025-09-20",
        pricePerKg: 380,
        currency: "THB",
        supplierNotes: "Winey, berry notes",
      },
    },
    {
      id: "GBL004",
      sourceType: GreenBeanSourceType.External,
      grade: "Grade B",
      initialWeightKg: 40,
      currentWeightKg: 40,
      availabilityStatus: "Available",
      cuppingScores: [],
      externalSource: {
        originName: "Colombia Huila Producer",
        variety: "Caturra",
        processType: "Washed",
        purchaseDate: "2025-10-05",
        pricePerKg: 320,
        currency: "THB",
      },
    },
  ],
  cuppingSessions: [
    {
      id: "CS001",
      name: "National Coffee Championship 2025",
      date: "2025-09-10",
      type: CuppingSessionType.Competition,
      status: "Adjudication",
      judges: [
        { id: "user-headjudge", name: "Artanis", role: UserRole.HeadJudge },
        { id: "user-cupper1", name: "Tassadar", role: UserRole.Cupper },
        { id: "user-cupper2", name: "Zeratul", role: UserRole.Cupper },
      ],
      samples: [
        {
          id: "S02",
          blindCode: "503",
          greenBeanLotId: "EXT01",
          submitterInfo: { name: "External Producer" },
          originInfo: { farm: "Some Other Farm" },
          lotInfo: { process: "Natural" },
        },
        {
          id: "S03",
          blindCode: "GBL003",
          greenBeanLotId: "GBL003",
          submitterInfo: { name: "Ethiopia Guji Cooperative" },
          originInfo: { farm: "Guji Highlands" },
          lotInfo: { process: "Natural" },
        },
      ],
      scores: {
        S02: [
          {
            judgeId: "user-cupper1",
            judgeName: "Tassadar",
            scores: {
              "Fragrance/Aroma": 8.25,
              Flavor: 8.0,
              Aftertaste: 7.75,
              Acidity: 8.0,
              Body: 8.5,
              Uniformity: 10,
              Balance: 8.0,
              "Clean Cup": 10,
              Sweetness: 10,
              Overall: 8.0,
            },
            totalScore: 86.5,
            notes: "Berry jam, winey notes. Full body.",
          },
          {
            judgeId: "user-cupper2",
            judgeName: "Zeratul",
            scores: {
              "Fragrance/Aroma": 8.5,
              Flavor: 8.25,
              Aftertaste: 8.0,
              Acidity: 7.75,
              Body: 8.25,
              Uniformity: 10,
              Balance: 7.75,
              "Clean Cup": 10,
              Sweetness: 10,
              Overall: 8.25,
            },
            totalScore: 86.75,
            notes:
              "Fermented fruit, dark chocolate. A bit rustic but enjoyable.",
          },
        ],
        S03: [
          {
            judgeId: "user-cupper1",
            judgeName: "Tassadar",
            scores: {
              "Fragrance/Aroma": 8.4,
              Flavor: 8.3,
              Aftertaste: 8.2,
              Acidity: 8.4,
              Body: 8.6,
              Uniformity: 10,
              Balance: 8.3,
              "Clean Cup": 10,
              Sweetness: 10,
              Overall: 8.4,
            },
            totalScore: 86.5,
            notes: "Blueberry jam, florals, plush mouthfeel.",
          },
          {
            judgeId: "user-cupper2",
            judgeName: "Zeratul",
            scores: {
              "Fragrance/Aroma": 8.6,
              Flavor: 8.4,
              Aftertaste: 8.1,
              Acidity: 8.3,
              Body: 8.4,
              Uniformity: 10,
              Balance: 8.2,
              "Clean Cup": 10,
              Sweetness: 10,
              Overall: 8.3,
            },
            totalScore: 86.8,
            notes: "Red berry compote, cocoa nib, lively acidity.",
          },
        ],
      },
      finalResults: {},
    },
    {
      id: "CS002",
      name: "Regional Qualifiers 2025",
      date: "2025-08-20",
      type: CuppingSessionType.Competition,
      status: "Scoring",
      judges: [
        { id: "user-headjudge", name: "Artanis", role: UserRole.HeadJudge },
        { id: "user-cupper1", name: "Tassadar", role: UserRole.Cupper },
        { id: "user-cupper3", name: "Fenix", role: UserRole.Cupper },
      ],
      samples: [
        {
          id: "S02",
          blindCode: "B22",
          greenBeanLotId: "EXT02",
          submitterInfo: { name: "Another Producer" },
          originInfo: { farm: "Finca Naranja" },
          lotInfo: { process: "Natural" },
        },
      ],
      scores: {
        S02: [
          {
            judgeId: "user-cupper1",
            judgeName: "Tassadar",
            scores: {
              "Fragrance/Aroma": 8.0,
              Flavor: 8.25,
              Aftertaste: 8.0,
              Acidity: 8.0,
              Body: 8.5,
              Uniformity: 10,
              Balance: 8.0,
              "Clean Cup": 10,
              Sweetness: 10,
              Overall: 8.0,
            },
            totalScore: 86.75,
            notes: "Fruity and sweet.",
          },
          {
            judgeId: "user-cupper3",
            judgeName: "Fenix",
            scores: {
              "Fragrance/Aroma": 8.25,
              Flavor: 8.0,
              Aftertaste: 7.75,
              Acidity: 8.0,
              Body: 8.25,
              Uniformity: 10,
              Balance: 8.0,
              "Clean Cup": 10,
              Sweetness: 10,
              Overall: 8.0,
            },
            totalScore: 86.25,
            notes: "Nice berry notes.",
          },
        ],
      },
    },
    {
      id: "CS003",
      name: "Producer Expo Showcase",
      date: "2025-10-01",
      type: CuppingSessionType.Competition,
      status: "Setup",
      judges: [
        { id: "user-headjudge", name: "Artanis", role: UserRole.HeadJudge },
        { id: "user-cupper2", name: "Zeratul", role: UserRole.Cupper },
      ],
      samples: [],
      scores: {},
    },
    {
      id: "CS004",
      name: "Golden Bean Award 2024",
      date: "2024-12-15",
      type: CuppingSessionType.Competition,
      status: "Finalized",
      judges: [
        { id: "user-headjudge", name: "Artanis", role: UserRole.HeadJudge },
        { id: "user-cupper1", name: "Tassadar", role: UserRole.Cupper },
        { id: "user-cupper2", name: "Zeratul", role: UserRole.Cupper },
      ],
      samples: [],
      scores: {},
      finalResults: {},
    },
  ],
  gapLogs: [],
  activityTypes: [
    {
      id: "AT001",
      name: "Fertilizer",
      description: "Application of fertilizers and nutrients",
      createdDate: "2025-01-01",
      isActive: true,
    },
    {
      id: "AT002",
      name: "Pest Management",
      description: "Pest control and management activities",
      createdDate: "2025-01-01",
      isActive: true,
    },
    {
      id: "AT003",
      name: "Water Management",
      description: "Irrigation and water management",
      createdDate: "2025-01-01",
      isActive: true,
    },
    {
      id: "AT004",
      name: "Pruning",
      description: "Tree pruning and maintenance",
      createdDate: "2025-01-01",
      isActive: true,
    },
    {
      id: "AT005",
      name: "Soil Management",
      description: "Soil preparation and management",
      createdDate: "2025-01-01",
      isActive: true,
    },
  ],
  processTypes: [
    {
      id: "PT001",
      name: "Washed",
      description:
        "Washed process - cherries are pulped and fermented to remove mucilage before drying",
      colorScheme: {
        borderColor: "border-l-blue-500",
        iconBg: "bg-blue-100",
        iconColor: "text-blue-600",
        badgeColor: "bg-blue-100 text-blue-700 border-blue-200",
      },
      createdDate: "2025-01-01",
      isActive: true,
    },
    {
      id: "PT002",
      name: "Natural",
      description:
        "Natural process - cherries are dried whole with the fruit intact",
      colorScheme: {
        borderColor: "border-l-amber-500",
        iconBg: "bg-amber-100",
        iconColor: "text-amber-600",
        badgeColor: "bg-amber-100 text-amber-700 border-amber-200",
      },
      createdDate: "2025-01-01",
      isActive: true,
    },
    {
      id: "PT003",
      name: "Honey",
      description:
        "Honey process - cherries are pulped but some or all mucilage is left on during drying",
      colorScheme: {
        borderColor: "border-l-yellow-500",
        iconBg: "bg-yellow-100",
        iconColor: "text-yellow-600",
        badgeColor: "bg-yellow-100 text-yellow-700 border-yellow-200",
      },
      createdDate: "2025-01-01",
      isActive: true,
    },
  ],
  soilAnalyses: [],
  roasterInventory: [],
  roastBatches: [],
  cropYears: [
    {
      id: "CY2024",
      year: "2024/2025",
      startDate: "2024-10-01",
      endDate: "2025-09-30",
      description: "Current crop year",
    },
    {
      id: "CY2023",
      year: "2023/2024",
      startDate: "2023-10-01",
      endDate: "2024-09-30",
      description: "Previous crop year",
    },
    {
      id: "CY2025",
      year: "2025/2026",
      startDate: "2025-10-01",
      endDate: "2026-09-30",
      description: "Next crop year",
    },
  ],
  weatherRecords: [],
  pricingHistory: [],
  customers: [
    {
      id: "CUST001",
      name: "Bangkok Coffee Roasters",
      type: "Roaster",
      contactEmail: "orders@bangkokcoffee.com",
      contactPhone: "02-123-4567",
      address: "123 Sukhumvit Rd, Bangkok 10110",
      notes: "Regular customer, pays on time",
    },
    {
      id: "CUST002",
      name: "Chiang Mai Specialty Coffee",
      type: "Distributor",
      contactEmail: "info@cmspecialty.com",
      contactPhone: "053-456-789",
      address: "456 Nimmanhaemin Rd, Chiang Mai 50200",
    },
    {
      id: "CUST003",
      name: "The Coffee Bean Shop",
      type: "Retailer",
      contactEmail: "shop@coffebean.co.th",
      contactPhone: "081-234-5678",
      address: "789 Pattaya Rd, Chonburi 20150",
      notes: "Prefers organic certified beans",
    },
  ],
  saleOrders: [],
  invoices: [],
};
