import { AppData, GreenBeanSourceType, ProcessingBatchStatus } from "./types";

// ============================================================
// ========== MOCK DATA - ลบส่วนนี้ได้เลยถ้าไม่ต้องการ ==========
// ============================================================

export const MOCK_DATA: AppData = {
  users: [],
  farms: [
    { id: "FARM001", farmerName: "ไร่กาแฟดอยช้าง", ownerNames: ["สมชาย ใจดี"], location: "เชียงราย", latitude: 19.9071, longitude: 99.8309, caretakerName: "สมชาย ใจดี", sizeHectares: 15.5, varieties: ["Gesha", "Caturra", "Typica"] },
    { id: "FARM002", farmerName: "สวนกาแฟดอยสุเทพ", ownerNames: ["วิไล สุขใจ"], location: "เชียงใหม่", latitude: 18.7883, longitude: 98.9853, caretakerName: "วิไล สุขใจ", sizeHectares: 8.2, varieties: ["Bourbon", "SL28"] },
    { id: "FARM003", farmerName: "ฟาร์มกาแฟแม่ฮ่องสอน", ownerNames: ["ประสิทธิ์ รักษ์ป่า"], location: "แม่ฮ่องสอน", latitude: 19.299, longitude: 97.9654, caretakerName: "ประสิทธิ์ รักษ์ป่า", sizeHectares: 12.0, varieties: ["Typica", "Catuai"] },
    { id: "FARM004", farmerName: "ไร่กาแฟน่าน", ownerNames: ["วิชัย ภูเขา"], location: "น่าน", latitude: 18.7756, longitude: 100.773, caretakerName: "วิชัย ภูเขา", sizeHectares: 10.0, varieties: ["Gesha", "Bourbon"] },
    { id: "FARM005", farmerName: "สวนกาแฟพะเยา", ownerNames: ["สุนทร ลำธาร"], location: "พะเยา", latitude: 19.1676, longitude: 99.9083, caretakerName: "สุนทร ลำธาร", sizeHectares: 7.5, varieties: ["SL34", "Pacamara"] },
    { id: "FARM006", farmerName: "ฟาร์มกาแฟลำปาง", ownerNames: ["นภา ดอยสูง"], location: "ลำปาง", latitude: 18.2888, longitude: 99.4906, caretakerName: "นภา ดอยสูง", sizeHectares: 9.8, varieties: ["Caturra", "Typica"] },
    { id: "FARM007", farmerName: "ไร่กาแฟตาก", ownerNames: ["ธนากร แม่สอด"], location: "ตาก", latitude: 16.8839, longitude: 99.1258, caretakerName: "ธนากร แม่สอด", sizeHectares: 11.2, varieties: ["Bourbon", "Catuai"] },
    { id: "FARM008", farmerName: "สวนกาแฟดอยอินทนนท์", ownerNames: ["อารีย์ ยอดดอย"], location: "เชียงใหม่", latitude: 18.5883, longitude: 98.4869, caretakerName: "อารีย์ ยอดดอย", sizeHectares: 18.0, varieties: ["Gesha", "SL28", "Bourbon"] },
    { id: "FARM009", farmerName: "ฟาร์มกาแฟเชียงราย", ownerNames: ["พิชัย ดอยตุง"], location: "เชียงราย", latitude: 20.2926, longitude: 99.8816, caretakerName: "พิชัย ดอยตุง", sizeHectares: 14.5, varieties: ["Typica", "Caturra"] },
    { id: "FARM010", farmerName: "ไร่กาแฟแม่แจ่ม", ownerNames: ["สมศักดิ์ หุบเขา"], location: "เชียงใหม่", latitude: 18.5048, longitude: 98.3638, caretakerName: "สมศักดิ์ หุบเขา", sizeHectares: 6.8, varieties: ["Pacamara", "SL34"] },
    { id: "FARM011", farmerName: "สวนกาแฟดอยวาวี", ownerNames: ["มาลี ชาวดอย"], location: "เชียงราย", latitude: 19.8652, longitude: 99.5648, caretakerName: "มาลี ชาวดอย", sizeHectares: 8.9, varieties: ["Gesha", "Bourbon"] },
    { id: "FARM012", farmerName: "ฟาร์มกาแฟขุนวาง", ownerNames: ["สุริยา ภูผา"], location: "เชียงใหม่", latitude: 19.0833, longitude: 98.5333, caretakerName: "สุริยา ภูผา", sizeHectares: 13.2, varieties: ["Caturra", "Catuai"] },
    { id: "FARM013", farmerName: "ไร่กาแฟปางมะโอ", ownerNames: ["วันชัย ป่าสน"], location: "เชียงใหม่", latitude: 19.2167, longitude: 98.8833, caretakerName: "วันชัย ป่าสน", sizeHectares: 5.5, varieties: ["SL28", "Typica"] },
    { id: "FARM014", farmerName: "สวนกาแฟห้วยน้ำดัง", ownerNames: ["บุญมา สายน้ำ"], location: "เชียงใหม่", latitude: 19.3167, longitude: 98.6, caretakerName: "บุญมา สายน้ำ", sizeHectares: 7.3, varieties: ["Bourbon", "Pacamara"] },
    { id: "FARM015", farmerName: "ฟาร์มกาแฟดอยหลวง", ownerNames: ["กิตติ ยอดภู"], location: "เชียงราย", latitude: 19.4833, longitude: 99.7833, caretakerName: "กิตติ ยอดภู", sizeHectares: 16.0, varieties: ["Gesha", "SL34", "Caturra"] },
  ],
  harvestLots: [
    { id: "HL001", farmId: "FARM001", farmerName: "สมชาย ใจดี", cherryVariety: "Gesha", weightKg: 150, farmPlotLocation: "แปลง A1", harvestDate: "2025-01-05", status: "Processing", cropYearId: "CY2024" },
    { id: "HL002", farmId: "FARM001", farmerName: "สมชาย ใจดี", cherryVariety: "Caturra", weightKg: 200, farmPlotLocation: "แปลง A2", harvestDate: "2025-01-08", status: "Processing", cropYearId: "CY2024" },
    { id: "HL003", farmId: "FARM002", farmerName: "วิไล สุขใจ", cherryVariety: "Bourbon", weightKg: 180, farmPlotLocation: "แปลง B1", harvestDate: "2025-01-10", status: "Ready for Processing", cropYearId: "CY2024" },
    { id: "HL004", farmId: "FARM002", farmerName: "วิไล สุขใจ", cherryVariety: "SL28", weightKg: 120, farmPlotLocation: "แปลง B2", harvestDate: "2025-01-12", status: "Ready for Processing", cropYearId: "CY2024" },
    { id: "HL005", farmId: "FARM003", farmerName: "ประสิทธิ์ รักษ์ป่า", cherryVariety: "Typica", weightKg: 250, farmPlotLocation: "แปลง C1", harvestDate: "2025-01-15", status: "Processing", cropYearId: "CY2024" },
    { id: "HL006", farmId: "FARM004", farmerName: "วิชัย ภูเขา", cherryVariety: "Gesha", weightKg: 175, farmPlotLocation: "แปลง D1", harvestDate: "2025-01-18", status: "Processing", cropYearId: "CY2024" },
    { id: "HL007", farmId: "FARM005", farmerName: "สุนทร ลำธาร", cherryVariety: "SL34", weightKg: 220, farmPlotLocation: "แปลง E1", harvestDate: "2025-01-20", status: "Ready for Processing", cropYearId: "CY2024" },
    { id: "HL008", farmId: "FARM006", farmerName: "นภา ดอยสูง", cherryVariety: "Caturra", weightKg: 190, farmPlotLocation: "แปลง F1", harvestDate: "2025-01-22", status: "Processing", cropYearId: "CY2024" },
    { id: "HL009", farmId: "FARM007", farmerName: "ธนากร แม่สอด", cherryVariety: "Bourbon", weightKg: 160, farmPlotLocation: "แปลง G1", harvestDate: "2025-01-25", status: "Ready for Processing", cropYearId: "CY2024" },
    { id: "HL010", farmId: "FARM008", farmerName: "อารีย์ ยอดดอย", cherryVariety: "Gesha", weightKg: 300, farmPlotLocation: "แปลง H1", harvestDate: "2025-01-28", status: "Processing", cropYearId: "CY2024" },
    { id: "HL011", farmId: "FARM009", farmerName: "พิชัย ดอยตุง", cherryVariety: "Typica", weightKg: 230, farmPlotLocation: "แปลง I1", harvestDate: "2025-02-01", status: "Processing", cropYearId: "CY2024" },
    { id: "HL012", farmId: "FARM010", farmerName: "สมศักดิ์ หุบเขา", cherryVariety: "Pacamara", weightKg: 140, farmPlotLocation: "แปลง J1", harvestDate: "2025-02-05", status: "Ready for Processing", cropYearId: "CY2024" },
    { id: "HL013", farmId: "FARM011", farmerName: "มาลี ชาวดอย", cherryVariety: "Bourbon", weightKg: 185, farmPlotLocation: "แปลง K1", harvestDate: "2025-02-08", status: "Processing", cropYearId: "CY2024" },
    { id: "HL014", farmId: "FARM012", farmerName: "สุริยา ภูผา", cherryVariety: "Catuai", weightKg: 210, farmPlotLocation: "แปลง L1", harvestDate: "2025-02-10", status: "Ready for Processing", cropYearId: "CY2024" },
    { id: "HL015", farmId: "FARM013", farmerName: "วันชัย ป่าสน", cherryVariety: "SL28", weightKg: 130, farmPlotLocation: "แปลง M1", harvestDate: "2025-02-12", status: "Processing", cropYearId: "CY2024" },
  ],
  processingBatches: [
    { id: "PB001", harvestLotId: "HL001", status: ProcessingBatchStatus.Completed, processType: "Washed", processNotes: "Fermented 36 hours", cropYearId: "CY2024", parchmentWeightKg: 30, moistureContent: 11.5, dryingStartDate: "2025-01-06", dryingEndDate: "2025-01-16" },
    { id: "PB002", harvestLotId: "HL002", status: ProcessingBatchStatus.Completed, processType: "Natural", processNotes: "Sun dried on raised beds", cropYearId: "CY2024", parchmentWeightKg: 40, moistureContent: 11.2, dryingStartDate: "2025-01-09", dryingEndDate: "2025-01-24" },
    { id: "PB003", harvestLotId: "HL005", status: ProcessingBatchStatus.Drying, processType: "Honey", processNotes: "Yellow honey process", cropYearId: "CY2024", dryingStartDate: "2025-01-16" },
    { id: "PB004", harvestLotId: "HL003", status: ProcessingBatchStatus.ToProcess, processType: "Washed", cropYearId: "CY2024" },
    { id: "PB005", harvestLotId: "HL006", status: ProcessingBatchStatus.Completed, processType: "Natural", processNotes: "African bed drying", cropYearId: "CY2024", parchmentWeightKg: 35, moistureContent: 11.0, dryingStartDate: "2025-01-19", dryingEndDate: "2025-02-03" },
    { id: "PB006", harvestLotId: "HL008", status: ProcessingBatchStatus.Drying, processType: "Washed", processNotes: "Extended fermentation 48h", cropYearId: "CY2024", dryingStartDate: "2025-01-23" },
    { id: "PB007", harvestLotId: "HL010", status: ProcessingBatchStatus.Completed, processType: "Honey", processNotes: "Red honey process", cropYearId: "CY2024", parchmentWeightKg: 60, moistureContent: 11.3, dryingStartDate: "2025-01-29", dryingEndDate: "2025-02-13" },
    { id: "PB008", harvestLotId: "HL011", status: ProcessingBatchStatus.Drying, processType: "Natural", processNotes: "Slow drying", cropYearId: "CY2024", dryingStartDate: "2025-02-02" },
    { id: "PB009", harvestLotId: "HL013", status: ProcessingBatchStatus.Completed, processType: "Washed", processNotes: "Clean fermentation", cropYearId: "CY2024", parchmentWeightKg: 37, moistureContent: 11.1, dryingStartDate: "2025-02-09", dryingEndDate: "2025-02-19" },
    { id: "PB010", harvestLotId: "HL015", status: ProcessingBatchStatus.ToProcess, processType: "Honey", cropYearId: "CY2024" },
    { id: "PB011", harvestLotId: "HL004", status: ProcessingBatchStatus.Completed, processType: "Natural", processNotes: "Patio dried", cropYearId: "CY2024", parchmentWeightKg: 24, moistureContent: 11.4, dryingStartDate: "2025-01-13", dryingEndDate: "2025-01-28" },
    { id: "PB012", harvestLotId: "HL007", status: ProcessingBatchStatus.Drying, processType: "Washed", cropYearId: "CY2024", dryingStartDate: "2025-01-21" },
    { id: "PB013", harvestLotId: "HL009", status: ProcessingBatchStatus.ToProcess, processType: "Natural", cropYearId: "CY2024" },
    { id: "PB014", harvestLotId: "HL012", status: ProcessingBatchStatus.Completed, processType: "Honey", processNotes: "Black honey", cropYearId: "CY2024", parchmentWeightKg: 28, moistureContent: 11.2, dryingStartDate: "2025-02-06", dryingEndDate: "2025-02-21" },
    { id: "PB015", harvestLotId: "HL014", status: ProcessingBatchStatus.Drying, processType: "Washed", processNotes: "72h fermentation", cropYearId: "CY2024", dryingStartDate: "2025-02-11" },
  ],
  parchmentLots: [
    { id: "PL001", processingBatchId: "PB001", harvestLotId: "HL001", initialWeightKg: 30, currentWeightKg: 28, moistureContent: 11.5, processType: "Washed", status: "Hulled" },
    { id: "PL002", processingBatchId: "PB002", harvestLotId: "HL002", initialWeightKg: 40, currentWeightKg: 40, moistureContent: 11.2, processType: "Natural", status: "Awaiting Hulling" },
    { id: "PL003", processingBatchId: "PB001", harvestLotId: "HL001", initialWeightKg: 25, currentWeightKg: 22, moistureContent: 11.0, processType: "Washed", status: "Hulled" },
    { id: "PL004", processingBatchId: "PB005", harvestLotId: "HL006", initialWeightKg: 35, currentWeightKg: 35, moistureContent: 11.0, processType: "Natural", status: "Awaiting Hulling" },
    { id: "PL005", processingBatchId: "PB007", harvestLotId: "HL010", initialWeightKg: 60, currentWeightKg: 58, moistureContent: 11.3, processType: "Honey", status: "Hulled" },
    { id: "PL006", processingBatchId: "PB009", harvestLotId: "HL013", initialWeightKg: 37, currentWeightKg: 37, moistureContent: 11.1, processType: "Washed", status: "Awaiting Hulling" },
    { id: "PL007", processingBatchId: "PB011", harvestLotId: "HL004", initialWeightKg: 24, currentWeightKg: 22, moistureContent: 11.4, processType: "Natural", status: "Hulled" },
    { id: "PL008", processingBatchId: "PB014", harvestLotId: "HL012", initialWeightKg: 28, currentWeightKg: 28, moistureContent: 11.2, processType: "Honey", status: "Awaiting Hulling" },
    { id: "PL009", processingBatchId: "PB002", harvestLotId: "HL002", initialWeightKg: 32, currentWeightKg: 30, moistureContent: 11.0, processType: "Natural", status: "Hulled" },
    { id: "PL010", processingBatchId: "PB005", harvestLotId: "HL006", initialWeightKg: 28, currentWeightKg: 26, moistureContent: 11.1, processType: "Natural", status: "Hulled" },
    { id: "PL011", processingBatchId: "PB007", harvestLotId: "HL010", initialWeightKg: 45, currentWeightKg: 45, moistureContent: 11.2, processType: "Honey", status: "Awaiting Hulling" },
    { id: "PL012", processingBatchId: "PB009", harvestLotId: "HL013", initialWeightKg: 30, currentWeightKg: 28, moistureContent: 11.0, processType: "Washed", status: "Hulled" },
    { id: "PL013", processingBatchId: "PB011", harvestLotId: "HL004", initialWeightKg: 20, currentWeightKg: 20, moistureContent: 11.3, processType: "Natural", status: "Awaiting Hulling" },
    { id: "PL014", processingBatchId: "PB014", harvestLotId: "HL012", initialWeightKg: 22, currentWeightKg: 20, moistureContent: 11.1, processType: "Honey", status: "Hulled" },
    { id: "PL015", processingBatchId: "PB001", harvestLotId: "HL001", initialWeightKg: 18, currentWeightKg: 18, moistureContent: 11.4, processType: "Washed", status: "Awaiting Hulling" },
  ],
  greenBeanLots: [
    { id: "GBL001", sourceType: GreenBeanSourceType.Internal, grade: "Grade A", initialWeightKg: 50, currentWeightKg: 45, availabilityStatus: "Available", cuppingScores: [{ sessionId: "CS001", score: 85.5 }], pricePerKg: 280, currency: "THB" },
    { id: "GBL002", sourceType: GreenBeanSourceType.Internal, grade: "Grade B", initialWeightKg: 80, currentWeightKg: 80, availabilityStatus: "Available", cuppingScores: [], pricePerKg: 220, currency: "THB" },
    { id: "GBL003", sourceType: GreenBeanSourceType.Internal, grade: "Peaberry", initialWeightKg: 25, currentWeightKg: 20, availabilityStatus: "Available", cuppingScores: [{ sessionId: "CS002", score: 88.0 }], pricePerKg: 350, currency: "THB" },
    { id: "GBL004", sourceType: GreenBeanSourceType.Internal, grade: "Screen 18", initialWeightKg: 60, currentWeightKg: 60, availabilityStatus: "Available", cuppingScores: [], pricePerKg: 300, currency: "THB" },
    { id: "GBL005", sourceType: GreenBeanSourceType.Internal, grade: "Grade C", initialWeightKg: 100, currentWeightKg: 95, availabilityStatus: "Withdrawn", cuppingScores: [], pricePerKg: 180, currency: "THB" },
    { id: "GBL006", sourceType: GreenBeanSourceType.Internal, grade: "Grade A", initialWeightKg: 70, currentWeightKg: 65, availabilityStatus: "Available", cuppingScores: [{ sessionId: "CS001", score: 86.0 }], pricePerKg: 290, currency: "THB" },
    { id: "GBL007", sourceType: GreenBeanSourceType.Internal, grade: "Screen 17", initialWeightKg: 45, currentWeightKg: 45, availabilityStatus: "Available", cuppingScores: [], pricePerKg: 260, currency: "THB" },
    { id: "GBL008", sourceType: GreenBeanSourceType.External, grade: "Grade A", initialWeightKg: 100, currentWeightKg: 100, availabilityStatus: "Available", cuppingScores: [{ sessionId: "CS001", score: 87.5 }], externalSource: { originName: "Ethiopia Yirgacheffe", variety: "Heirloom", processType: "Natural", purchaseDate: "2025-01-10", pricePerKg: 450, currency: "THB", supplierNotes: "Blueberry, floral notes" } },
    { id: "GBL009", sourceType: GreenBeanSourceType.External, grade: "Grade A", initialWeightKg: 75, currentWeightKg: 70, availabilityStatus: "Available", cuppingScores: [{ sessionId: "CS002", score: 86.0 }], externalSource: { originName: "Colombia Huila", variety: "Caturra", processType: "Washed", purchaseDate: "2025-01-15", pricePerKg: 380, currency: "THB", supplierNotes: "Citrus, caramel sweetness" } },
    { id: "GBL010", sourceType: GreenBeanSourceType.External, grade: "Grade B", initialWeightKg: 50, currentWeightKg: 50, availabilityStatus: "Available", cuppingScores: [], externalSource: { originName: "Kenya AA", variety: "SL28", processType: "Washed", purchaseDate: "2025-01-20", pricePerKg: 520, currency: "THB" } },
    { id: "GBL011", sourceType: GreenBeanSourceType.External, grade: "Peaberry", initialWeightKg: 30, currentWeightKg: 30, availabilityStatus: "Available", cuppingScores: [{ sessionId: "CS001", score: 89.0 }], externalSource: { originName: "Guatemala Antigua", variety: "Bourbon", processType: "Honey", purchaseDate: "2025-01-25", pricePerKg: 400, currency: "THB", supplierNotes: "Chocolate, nuts, full body" } },
    { id: "GBL012", sourceType: GreenBeanSourceType.External, grade: "Screen 17", initialWeightKg: 80, currentWeightKg: 75, availabilityStatus: "Withdrawn", cuppingScores: [], externalSource: { originName: "Costa Rica Tarrazu", variety: "Catuai", processType: "Natural", purchaseDate: "2025-01-05", pricePerKg: 360, currency: "THB" } },
    { id: "GBL013", sourceType: GreenBeanSourceType.External, grade: "Grade A", initialWeightKg: 60, currentWeightKg: 60, availabilityStatus: "Available", cuppingScores: [{ sessionId: "CS002", score: 87.0 }], externalSource: { originName: "Panama Gesha", variety: "Gesha", processType: "Washed", purchaseDate: "2025-02-01", pricePerKg: 850, currency: "THB", supplierNotes: "Jasmine, bergamot" } },
    { id: "GBL014", sourceType: GreenBeanSourceType.External, grade: "Grade B", initialWeightKg: 90, currentWeightKg: 85, availabilityStatus: "Available", cuppingScores: [], externalSource: { originName: "Brazil Santos", variety: "Mundo Novo", processType: "Natural", purchaseDate: "2025-02-05", pricePerKg: 280, currency: "THB" } },
    { id: "GBL015", sourceType: GreenBeanSourceType.External, grade: "Screen 18", initialWeightKg: 55, currentWeightKg: 55, availabilityStatus: "Available", cuppingScores: [{ sessionId: "CS001", score: 85.0 }], externalSource: { originName: "Indonesia Sumatra", variety: "Mandheling", processType: "Wet Hulled", purchaseDate: "2025-02-10", pricePerKg: 340, currency: "THB", supplierNotes: "Earthy, herbal, full body" } },
  ],
  cuppingSessions: [],
  gapLogs: [],
  activityTypes: [
    { id: "AT001", name: "Fertilizer", description: "Application of fertilizers and nutrients", createdDate: "2025-01-01", isActive: true },
    { id: "AT002", name: "Pest Management", description: "Pest control and management activities", createdDate: "2025-01-01", isActive: true },
    { id: "AT003", name: "Water Management", description: "Irrigation and water management", createdDate: "2025-01-01", isActive: true },
    { id: "AT004", name: "Pruning", description: "Tree pruning and maintenance", createdDate: "2025-01-01", isActive: true },
    { id: "AT005", name: "Soil Management", description: "Soil preparation and management", createdDate: "2025-01-01", isActive: true },
  ],
  processTypes: [
    { id: "PT001", name: "Washed", description: "Washed process - cherries are pulped and fermented to remove mucilage before drying", colorScheme: { borderColor: "border-l-blue-500", iconBg: "bg-blue-100", iconColor: "text-blue-600", badgeColor: "bg-blue-100 text-blue-700 border-blue-200" }, createdDate: "2025-01-01", isActive: true },
    { id: "PT002", name: "Natural", description: "Natural process - cherries are dried whole with the fruit intact", colorScheme: { borderColor: "border-l-amber-500", iconBg: "bg-amber-100", iconColor: "text-amber-600", badgeColor: "bg-amber-100 text-amber-700 border-amber-200" }, createdDate: "2025-01-01", isActive: true },
    { id: "PT003", name: "Honey", description: "Honey process - cherries are pulped but some or all mucilage is left on during drying", colorScheme: { borderColor: "border-l-yellow-500", iconBg: "bg-yellow-100", iconColor: "text-yellow-600", badgeColor: "bg-yellow-100 text-yellow-700 border-yellow-200" }, createdDate: "2025-01-01", isActive: true },
  ],
  soilAnalyses: [],
  roasterInventory: [],
  roastBatches: [],
  cropYears: [
    { id: "CY2024", year: "2024/2025", startDate: "2024-10-01", endDate: "2025-09-30", description: "Current crop year" },
    { id: "CY2023", year: "2023/2024", startDate: "2023-10-01", endDate: "2024-09-30", description: "Previous crop year" },
    { id: "CY2025", year: "2025/2026", startDate: "2025-10-01", endDate: "2026-09-30", description: "Next crop year" },
  ],
  weatherRecords: [],
  pricingHistory: [],
  customers: [
    { id: "CUST001", name: "กาแฟคั่วบางกอก", type: "Roaster", contactEmail: "orders@bangkokcoffee.com", contactPhone: "02-123-4567", address: "123 ถนนสุขุมวิท กรุงเทพฯ 10110", notes: "ลูกค้าประจำ ชำระตรงเวลา" },
    { id: "CUST002", name: "เชียงใหม่สเปเชียลตี้", type: "Distributor", contactEmail: "info@cmspecialty.com", contactPhone: "053-456-789", address: "456 ถนนนิมมานเหมินท์ เชียงใหม่ 50200" },
    { id: "CUST003", name: "ร้านเมล็ดกาแฟ", type: "Retailer", contactEmail: "shop@coffeebean.co.th", contactPhone: "081-234-5678", address: "789 ถนนพัทยา ชลบุรี 20150", notes: "ต้องการเมล็ดออร์แกนิค" },
    { id: "CUST004", name: "คาเฟ่ริมน้ำ", type: "Other", contactEmail: "cafe@riverside.com", contactPhone: "02-987-6543", address: "321 ถนนเจริญกรุง กรุงเทพฯ 10500" },
    { id: "CUST005", name: "โรงคั่วภูเขา", type: "Roaster", contactEmail: "mountain@roaster.com", contactPhone: "054-111-2222", address: "555 ถนนพหลโยธิน ลำปาง 52000", notes: "สั่งซื้อเป็นประจำทุกเดือน" },
    { id: "CUST006", name: "กาแฟสดภูเก็ต", type: "Retailer", contactEmail: "phuket@freshcoffee.com", contactPhone: "076-222-333", address: "100 ถนนถลาง ภูเก็ต 83000" },
    { id: "CUST007", name: "ดิสทริบิวเตอร์อีสาน", type: "Distributor", contactEmail: "isan@coffee.com", contactPhone: "043-333-444", address: "200 ถนนมิตรภาพ ขอนแก่น 40000", notes: "กระจายสินค้าภาคอีสาน" },
    { id: "CUST008", name: "คาเฟ่มหาวิทยาลัย", type: "Other", contactEmail: "unicafe@edu.com", contactPhone: "02-555-6666", address: "มหาวิทยาลัยธรรมศาสตร์ กรุงเทพฯ" },
    { id: "CUST009", name: "โรงคั่วเชียงราย", type: "Roaster", contactEmail: "cr@roaster.com", contactPhone: "053-777-888", address: "88 ถนนพหลโยธิน เชียงราย 57000" },
    { id: "CUST010", name: "ร้านกาแฟหาดใหญ่", type: "Retailer", contactEmail: "hatyai@coffee.com", contactPhone: "074-444-555", address: "150 ถนนนิพัทธ์อุทิศ สงขลา 90110" },
    { id: "CUST011", name: "ตัวแทนจำหน่ายใต้", type: "Distributor", contactEmail: "south@dist.com", contactPhone: "075-666-777", address: "300 ถนนราชดำเนิน นครศรีธรรมราช 80000" },
    { id: "CUST012", name: "คาเฟ่อารีย์", type: "Other", contactEmail: "ari@cafe.com", contactPhone: "02-888-9999", address: "55 ซอยอารีย์ กรุงเทพฯ 10400", notes: "ร้านยอดนิยมย่านอารีย์" },
    { id: "CUST013", name: "โรงคั่วหัวหิน", type: "Roaster", contactEmail: "huahin@roast.com", contactPhone: "032-111-222", address: "77 ถนนเพชรเกษม ประจวบคีรีขันธ์ 77110" },
    { id: "CUST014", name: "ร้านกาแฟพิษณุโลก", type: "Retailer", contactEmail: "phitsanulok@coffee.com", contactPhone: "055-333-444", address: "200 ถนนบรมไตรโลกนาถ พิษณุโลก 65000" },
    { id: "CUST015", name: "กลุ่มโรงแรมไทย", type: "Other", contactEmail: "hotels@thai.com", contactPhone: "02-000-1111", address: "999 ถนนสีลม กรุงเทพฯ 10500", notes: "สั่งซื้อจำนวนมากทุกไตรมาส" },
  ],
  saleOrders: [],
  invoices: [],
};
